language: swift
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
script:
  - ./Scripts/ci.sh
matrix:
  include:
  - osx_image: xcode11.2
    env: ACTION="swift-package";PLATFORMS="iOS_12,iOS_13";

  - osx_image: xcode11.2
    env: ACTION="swift-package";PLATFORMS="tvOS_12,tvOS_13";
    after_success:
      - bash <(curl -s https://codecov.io/bash) -J '^CacheAdvance$' -D .build/derivedData/tvOS_12 -t 8344b011-6b2a-4b3d-a573-eaf49684318e
      - bash <(curl -s https://codecov.io/bash) -J '^CacheAdvance$' -D .build/derivedData/tvOS_13 -t 8344b011-6b2a-4b3d-a573-eaf49684318e

  - osx_image: xcode11.2
    env: ACTION="swift-package";PLATFORMS="macOS_10_15";

  - osx_image: xcode11.2
    env: ACTION="swift-package";PLATFORMS="watchOS_5,watchOS_6";

  - osx_image: xcode11.2
    env: ACTION="pod-lint";SWIFT_VERSION="5.1"

  - osx_image: xcode11.2
    env: ACTION="carthage"

branches:
  only:
  - master
