language: objective-c
install:
  - bundle install
  - brew outdated carthage || brew upgrade carthage
script:
  - ./Scripts/ci.sh
matrix:
  include:
  - osx_image: xcode11.2
    env: ACTION="swift-package";SDK="iphonesimulator";DESTINATION="platform=iOS Simulator,OS=13.2.2,name=iPad Pro (12.9-inch) (3rd generation)"
    after_success:
      sh <(curl -s https://codecov.io/bash) -J '^CacheAdvance$' -D .build/derivedData
  - osx_image: xcode11.2
    env: ACTION="swift-package";SDK="appletvsimulator13.2";DESTINATION="platform=tvOS Simulator,name=Apple TV"
  - osx_image: xcode11.2
    env: ACTION="swift-package";SDK="macosx10.15";DESTINATION="platform=OS X"
  - osx_image: xcode11.2
    env: ACTION="swift-package";SDK="watchos6.1";DESTINATION=""
