codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

coverage:
  status:
    project:
      default:
        threshold: 0.25%
    patch: off

ignore:
  # Due to limitations in Github Actions' supported Xcode versions, we can't get good coverage on this file.
  - "Sources/CacheAdvance/FileHandleExtensions.swift"
  # This package is not shipped and only includes testing helpers.
  - "Sources/LorumIpsum"
  # This package is not shipped.
  - "Tests"
