name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  pod-lint:
    name: Pod Lint
    runs-on: macOS-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_11.7.app/Contents/Developer
      - name: Lint Podspec
        run: bundle exec pod lib lint --verbose --fail-fast --swift-version=5.1
  carthage:
    name: Carthage
    runs-on: macOS-10.15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_11.7.app/Contents/Developer
      - name: Install Carthage
        run: brew outdated carthage || brew upgrade carthage
      - name: Build Framework
        run: swift package generate-xcodeproj --output generated/ && carthage build --project-directory generated/ --verbose --no-skip-current
  spm-11:
    name: SPM Build Xcode 11
    runs-on: macOS-10.15
    strategy:
      matrix:
        platforms: [
          'iOS_12,tvOS_12',
          'iOS_13,tvOS_13,watchOS_6',
          'macOS_10_15'
        ]
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_11.7.app/Contents/Developer
      - name: Prepare Simulator Runtimes
        run: Scripts/github/prepare-simulators.sh ${{ matrix.platforms }}
      - name: Build and Test Framework
        run: Scripts/build.swift ${{ matrix.platforms }}
      - name: Upload Coverage Reports
        if: success()
        run: Scripts/upload-coverage-reports.sh ${{ matrix.platforms }}
  spm-12:
    name: SPM Build Xcode 12
    runs-on: macOS-10.15
    strategy:
      matrix:
        platforms: [
          'iOS_14,tvOS_14,watchOS_7',
        ]
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Bundle Install
        run: bundle install
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_12.4.app/Contents/Developer
      - name: Prepare Simulator Runtimes
        run: Scripts/github/prepare-simulators.sh ${{ matrix.platforms }}
      - name: Build and Test Framework
        run: Scripts/build.swift ${{ matrix.platforms }}
      - name: Upload Coverage Reports
        if: success()
        run: Scripts/upload-coverage-reports.sh ${{ matrix.platforms }}
